//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template4333
{
    using System;
    using System.Collections.Generic;
    
    public partial class Info
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Type_of_service { get; set; }
        public string Id_service { get; set; }
        public Nullable<int> Cost_rub { get; set; }
    }
}
