//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template4333
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json;
    using System.Text.Json.Serialization;


    public partial class Info
    {
        public int ID { get; set; }
     
        [JsonPropertyName("NameServices")]
        public string Name { get; set; }
        
        [JsonPropertyName("TypeOfService")]
        public string Type_of_service { get; set; }
      
        [JsonPropertyName("CodeService")]
        public string Id_service { get; set; }
       
        [JsonPropertyName("Cost")]
        public int Cost_rub { get; set; }
        
    }
}

