//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Text.Json;
using System.Text.Json.Serialization;
namespace Template4333
{
    using System;
    using System.Collections.Generic;
    
    public partial class ISRPO3
    {
        public int Id { get; set; }
        
        public string FIO { get; set; }
	
		public string ClienID { get; set; }
	
		public string DateBirth { get; set; }
		
		public string Indeks { get; set; }
		public string City { get; set; }
		
		public string Ulitca { get; set; }
		
		public string Home { get; set; }
		public string Kvartira { get; set; }
		

		public string Email { get; set; }
    }
}
