//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template4333
{
    using System;
    using System.Collections.Generic;
    
    public partial class laba3isr
    {
        public int id { get; set; }
        public string kod_zakaza { get; set; }
        public string Data_sozdania { get; set; }
        public string Vremya_zakaza { get; set; }
        public string kod_klienta { get; set; }
        public string uslugi { get; set; }
        public string statuz { get; set; }
        public string data_zakritia { get; set; }
        public string vremya_prokata { get; set; }
    }
}
