//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template4333
{
    using System;
    using System.Collections.Generic;
    
    public partial class s_ervice
    {
        public int id { get; set; }
        public string name_service { get; set; }
        public string type_of_service { get; set; }
        public string code_service { get; set; }
        public Nullable<int> price { get; set; }
    }
}
