//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template4333
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int ID { get; set; }
        public string Code_order { get; set; }
        public string Data { get; set; }
        public string Time { get; set; }
        public string Code_client { get; set; }
        public string Uslugi { get; set; }
        public string Status { get; set; }
        public string Data_close { get; set; }
        public string Time_prokata { get; set; }
    }
}
