//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template4333
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;

    public partial class User
    {
        [JsonPropertyName("IdServices")]
        public int ID { get; set; }
        [JsonPropertyName("NameServices")]
        public string Наименование_услуги { get; set; }
        [JsonPropertyName("TypeOfService")]
        public string Вид_услуги { get; set; }
        [JsonPropertyName("Cost")]
        public int Стоимость { get; set; }
    }
}
