//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Text.Json;
using System.Text.Json.Serialization;
namespace Template4333
{
    using System;
    using System.Collections.Generic;
    
    public partial class xls1
    {
        public int Id { get; set; }
        public string CodeStaff { get; set; }
        public string Position { get; set; }
        public string FullName { get; set; }
        [JsonPropertyName("Log")]
        public string Lg { get; set; }
        [JsonPropertyName("Password")]
        public string Pass { get; set; }
        public string LastEnter { get; set; }
        public string TypeEnter { get; set; }
    }
}
