//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template4333.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;Initial Catalog=C:\\USERS\\YURIC\\DOWNLOADS\\TEMPL" +
            "ATE4333\\TEMPLATE4333\\TEMPLATE4333\\DATABASE.MDF;Integrated Security=True;TrustSer" +
            "verCertificate=True")]
        public string C__USERS_YURIC_DOWNLOADS_TEMPLATE4333_TEMPLATE4333_TEMPLATE4333_DATABASE_MDFConnectionString {
            get {
                return ((string)(this["C__USERS_YURIC_DOWNLOADS_TEMPLATE4333_TEMPLATE4333_TEMPLATE4333_DATABASE_MDFConne" +
                    "ctionString"]));
            }
        }
    }
}
